- name: Demo in Template
  hosts: localhost
  tasks:
    - name: Copy example.conf                   # example for copy
      ansible.builtin.copy:
        src: example.conf
        dest: /tmp/example-copy.conf