- name: Demo in Template
  hosts: localhost
  tasks:
    - name: Copy example.conf                   # example for copy
      ansible.builtin.copy:
        src: example.conf
        dest: /tmp/example-copy.conf

    - name: Template example.conf                   # example for template
      ansible.builtin.template:
        src: example.conf
        dest: /tmp/example-template.conf




# while copy the files some dynamic  content needs to be updated you have to go with template