- name: Demo on tags
  hosts: localhost
  tasks:
    - name: Vegetables
      ansible.builtin.debug:
        msg: Vegetables
      tags: "Vegetables"

    - name: Fruits
      ansible.builtin.debug:
        msg: Fruits
      tags: "Fruits"