- name: demo on loops
  hosts: localhost
  tasks:
    - name: print Fruits
      ansible.builtin.debug:
        msg: fruit Name -{{ item }}
      loop:
        - apple
        - banana
        - orange